# -*- coding: utf-8 -*-
"""ancova.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZ10X7Q8f_32B6c6AXT-jAmASapNsRMV
"""

import pandas as pd
df=pd.read_csv("/content/INF2178_A3_data.csv")
df.head(10)

# Display information on dataset
print(df.info())

# Check for NaN values
nan_count = df.isna().sum()
print(nan_count)

# Create continuous variables on General Knowledge score
df['generallknowledge'] = (df['fallgeneralknowledgescore'] + df['springgeneralknowledgescore'])/2
df['generallknowledge']

# Calculate Educational Improvement for reading, math, and general knowledge
df['Reading_Gain'] = df['springreadingscore'] - df['fallreadingscore']
df['Math_Gain'] = df['springmathscore'] - df['fallmathscore']
df['GeneralKnowledge_Gain'] = df['springgeneralknowledgescore'] - df['fallgeneralknowledgescore']
print (df['Reading_Gain'], df['Math_Gain'], df['GeneralKnowledge_Gain'] )

# Summary Statistics
# Function for summary statistics
def get_summary_statistics(dataset, label='Dataset'):

    mean = np.round(np.mean(dataset), 2)
    median = np.round(np.median(dataset), 2)
    min_value = np.round(dataset.min(), 2)
    max_value = np.round(dataset.max(), 2)
    quartile_1 = np.round(dataset.quantile(0.25), 2)
    quartile_3 = np.round(dataset.quantile(0.75), 2)

    # Interquartile range
    iqr = np.round(quartile_3 - quartile_1, 2)

    print(f'{label} Summary Statistics:')
    print('Min: %s' % min_value)
    print('Mean: %s' % mean)
    print('Max: %s' % max_value)
    print('25th percentile: %s' % quartile_1)
    print('Median: %s' % median)
    print('75th percentile: %s' % quartile_3)
    print('Interquartile range (IQR): %s' % iqr)
    print('\n\n')

# Display summary statistics
get_summary_statistics(df['fallreadingscore'], 'Fall Reading Score')
get_summary_statistics(df['fallmathscore'], 'Fall Math Score')
get_summary_statistics(df['fallgeneralknowledgescore'], 'Fall General Knowledge Score')
get_summary_statistics(df['springreadingscore'], 'Spring Reading Score')
get_summary_statistics(df['springmathscore'], 'Spring Math Score')
get_summary_statistics(df['springgeneralknowledgescore'], 'Spring General Knowledge Score')
get_summary_statistics(df['totalhouseholdincome'], 'Total Household Income')
get_summary_statistics(df['incomeinthousands'], 'Income in Thousands')
get_summary_statistics(df['incomegroup'], 'Income Group')

# Commented out IPython magic to ensure Python compatibility.
# %pip install dfply
from dfply import *
# summary statistics for dependent variable yield
summary_statistics = df >> group_by(X.incomegroup) >> summarize(n=X['generallknowledge'].count(),
                                                                mean=X['generallknowledge'].mean(),
                                                                std=X['generallknowledge'].std())
summary_statistics

import seaborn as sns
import matplotlib.pyplot as plt
fig, axs = plt.subplots(ncols=3, figsize=(18, 6))
# Scatter plot for 'fallmathscore' vs 'springmathscore' colored by 'incomegroup'
sns.scatterplot(data=df, x="fallgeneralknowledgescore", y="springgeneralknowledgescore", hue="incomegroup", palette="viridis", ax=axs[0])
# Boxplot for 'springmathscore' by 'incomegroup'
sns.boxplot(data=df, x="incomegroup", y="springgeneralknowledgescore", palette="viridis", ax=axs[1])
# Boxplot for 'totalhouseholdincome' by 'incomegroup'
sns.boxplot(data=df, x="incomegroup", y="fallgeneralknowledgescore", palette="viridis", ax=axs[2])
plt.tight_layout()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %pip install pingouin
from pingouin import ancova
ancova_results = ancova(data=df, dv='springgeneralknowledgescore', covar='fallgeneralknowledgescore', between='incomegroup')
print(ancova_results)

import numpy as np
import pandas as pd
data = df[['incomegroup', 'fallgeneralknowledgescore', 'springgeneralknowledgescore']].copy()
print(data.head(12))

from pingouin import ancova
ancova_results = ancova(data=sample_data, dv='fallgeneralknowledgescore', covar='springgeneralknowledgescore', between='incomegroup')
print(ancova_results)

#ancova using statsmodels
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform the ANCOVA
model = ols('springgeneralknowledgescore ~ C(incomegroup) + fallgeneralknowledgescore', data=data).fit()
# Print the summary of the model
print(model.summary())

import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Fit ANCOVA model
model = ols('springgeneralknowledgescore ~ C(incomegroup) + fallgeneralknowledgescore', data=data).fit()
# Print model summary
print(model.summary())

# Fit ANCOVA model with interaction term
model_interaction = ols('springgeneralknowledgescore ~ C(incomegroup) * fallgeneralknowledgescore', data=data).fit()
# Print model summary
print(model_interaction.summary())